name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run lint
        run: | 
          yarn lint
          yarn format-check
      - name: Run tests
        run: yarn test
