name: CI
on: push

env:
  NODE_VERSION: '14'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Clean caches
        run: yarn cache clean
      - name: Install modules
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run prettier
        run: yarn format-check
      - name: Run tests
        run: yarn test
